plugins {
    id 'java'
}

project.ext.lwjglVersion = "3.4.3"
project.ext.lwjglNatives = "natives-windows"

group = 'org.frontier'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-opengl::$lwjglNatives"

    runtimeOnly "org.lwjgl:lwjgl:3.4.3:natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-glfw:3.4.3:natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-opengl:3.4.3:natives-windows"
}

test {
    useJUnitPlatform()
}